/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TabelaPrecoLinha = IDL.Record({
  'descricao' : IDL.Text,
  'colunas' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ItemOrcamento = IDL.Record({
  'nomeMaterial' : IDL.Text,
  'descricao' : IDL.Text,
  'precoUnitario' : IDL.Nat,
  'quantidade' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const Cliente = IDL.Record({
  'id' : IDL.Nat,
  'nif' : IDL.Text,
  'contato' : IDL.Text,
  'nome' : IDL.Text,
  'morada' : IDL.Text,
});
export const PrecoFornecedor = IDL.Record({
  'fornecedor' : IDL.Text,
  'data' : IDL.Int,
  'vendedor' : IDL.Text,
  'contatoVendedor' : IDL.Text,
  'preco' : IDL.Nat,
});
export const Material = IDL.Record({
  'id' : IDL.Nat,
  'nome' : IDL.Text,
  'precos' : IDL.Vec(PrecoFornecedor),
});
export const StatusOrcamento = IDL.Variant({
  'aceito' : IDL.Null,
  'pendente' : IDL.Null,
  'rejeitado' : IDL.Null,
});
export const Empresa = IDL.Record({
  'cae' : IDL.Text,
  'nib' : IDL.Text,
  'alvara' : IDL.Text,
  'nome' : IDL.Text,
  'email' : IDL.Text,
  'logoPath' : IDL.Text,
  'morada' : IDL.Text,
  'telefone' : IDL.Text,
});
export const Orcamento = IDL.Record({
  'id' : IDL.Nat,
  'iva' : IDL.Nat,
  'desconto' : IDL.Nat,
  'status' : StatusOrcamento,
  'condicoesFornecimento' : IDL.Text,
  'imagemAdicionalPath' : IDL.Opt(IDL.Text),
  'validadeOrcamento' : IDL.Text,
  'observacoes' : IDL.Text,
  'gestor' : IDL.Text,
  'itens' : IDL.Vec(ItemOrcamento),
  'empresa' : Empresa,
  'clienteId' : IDL.Nat,
  'dataOrcamento' : IDL.Int,
  'valorTotal' : IDL.Nat,
});
export const Status = IDL.Variant({
  'encomenda' : IDL.Null,
  'concluido' : IDL.Null,
  'montagem' : IDL.Null,
  'producao' : IDL.Null,
  'porPagar' : IDL.Null,
});
export const Encomenda = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'contato' : IDL.Text,
  'descricao' : IDL.Text,
  'dataCriacao' : IDL.Int,
  'gestor' : IDL.Text,
  'valorAdiantado' : IDL.Nat,
  'nomeCliente' : IDL.Text,
  'valorTotal' : IDL.Nat,
});
export const RelatorioPDF = IDL.Record({
  'gestor' : IDL.Text,
  'encomendas' : IDL.Vec(Encomenda),
});
export const ResumoFinanceiro = IDL.Record({
  'totalValor' : IDL.Nat,
  'totalEncomendas' : IDL.Nat,
  'totalPendente' : IDL.Nat,
  'totalAdiantado' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Movimentacao = IDL.Record({
  'statusAnterior' : Status,
  'timestamp' : IDL.Int,
  'novoStatus' : Status,
});
export const Gestor = IDL.Record({ 'nome' : IDL.Text });
export const TabelaPrecoCategoria = IDL.Record({
  'categoria' : IDL.Text,
  'titulosColunas' : IDL.Vec(IDL.Text),
  'linhas' : IDL.Vec(TabelaPrecoLinha),
});
export const Rodape = IDL.Record({ 'textoCompleto' : IDL.Text });
export const DadosCompletos = IDL.Record({
  'clientes' : IDL.Vec(Cliente),
  'lastEditTime' : IDL.Int,
  'orcamentos' : IDL.Vec(Orcamento),
  'historico' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(Movimentacao))),
  'nextId' : IDL.Nat,
  'gestores' : IDL.Vec(Gestor),
  'materiais' : IDL.Vec(Material),
  'encomendas' : IDL.Vec(Encomenda),
  'tabelasPreco' : IDL.Vec(TabelaPrecoCategoria),
  'nextOrcamentoId' : IDL.Nat,
  'rodape' : IDL.Opt(Rodape),
  'nextMaterialId' : IDL.Nat,
  'empresa' : IDL.Opt(Empresa),
  'nextClienteId' : IDL.Nat,
  'backups' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const BackupInfo = IDL.Record({
  'id' : IDL.Nat,
  'descricao' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'aceitarOrcamento' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'mensagem' : IDL.Text,
          'encomendaId' : IDL.Opt(IDL.Nat),
          'sucesso' : IDL.Bool,
        }),
      ],
      [],
    ),
  'adicionarGestor' : IDL.Func([IDL.Text], [], []),
  'adicionarLinhaTabela' : IDL.Func([IDL.Text, TabelaPrecoLinha], [], []),
  'adicionarMaterial' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'adicionarPrecoFornecedor' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'atualizarEmpresa' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'atualizarLinhaTabela' : IDL.Func(
      [IDL.Text, TabelaPrecoLinha, IDL.Nat],
      [],
      [],
    ),
  'atualizarRodape' : IDL.Func([IDL.Text], [], []),
  'atualizarStatus' : IDL.Func([IDL.Nat], [], []),
  'atualizarTituloColuna' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'criarBackup' : IDL.Func(
      [],
      [IDL.Record({ 'backupId' : IDL.Nat, 'mensagem' : IDL.Text })],
      [],
    ),
  'criarCliente' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'criarEncomenda' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'criarOrcamento' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Vec(ItemOrcamento),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'deletarCliente' : IDL.Func([IDL.Nat], [], []),
  'deletarEncomenda' : IDL.Func([IDL.Nat], [], []),
  'deletarItemOrcamento' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'deletarMaterial' : IDL.Func([IDL.Nat], [], []),
  'deletarOrcamento' : IDL.Func([IDL.Nat], [], []),
  'deletarPrecoFornecedor' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'editarCliente' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'editarEncomenda' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'editarMaterial' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'editarOrcamento' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(ItemOrcamento),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'editarPrecoFornecedor' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'eliminarBackup' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'mensagem' : IDL.Text })],
      [],
    ),
  'eliminarLinha' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'filtrarClientesPorNome' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Cliente)],
      ['query'],
    ),
  'filtrarMateriaisPorFornecedor' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Material)],
      ['query'],
    ),
  'filtrarMateriaisPorNome' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Material)],
      ['query'],
    ),
  'filtrarOrcamentosPorGestor' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Orcamento)],
      ['query'],
    ),
  'filtrarOrcamentosPorGestorENomeCliente' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Orcamento)],
      ['query'],
    ),
  'filtrarOrcamentosPorNomeCliente' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Orcamento)],
      ['query'],
    ),
  'filtrarPorGestorEStatus' : IDL.Func(
      [IDL.Text, Status],
      [IDL.Vec(Encomenda)],
      ['query'],
    ),
  'gerarRelatorioPDF' : IDL.Func(
      [Status, IDL.Opt(IDL.Text)],
      [
        IDL.Record({
          'relatorios' : IDL.Vec(RelatorioPDF),
          'resumoFinanceiro' : ResumoFinanceiro,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCliente' : IDL.Func([IDL.Nat], [IDL.Opt(Cliente)], ['query']),
  'getDadosCompletos' : IDL.Func([], [DadosCompletos], []),
  'getDadosOrcamentoPDF' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({
            'rodape' : IDL.Opt(Rodape),
            'empresa' : Empresa,
            'orcamento' : Orcamento,
            'imagemAdicional' : IDL.Opt(FileReference),
            'cliente' : Cliente,
          })
        ),
      ],
      ['query'],
    ),
  'getEmpresa' : IDL.Func([], [IDL.Opt(Empresa)], ['query']),
  'getEncomenda' : IDL.Func([IDL.Nat], [IDL.Opt(Encomenda)], ['query']),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getHistorico' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(Movimentacao))],
      ['query'],
    ),
  'getMaterial' : IDL.Func([IDL.Nat], [IDL.Opt(Material)], ['query']),
  'getOrcamento' : IDL.Func([IDL.Nat], [IDL.Opt(Orcamento)], ['query']),
  'getOrcamentoCompleto' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Record({ 'orcamento' : Orcamento, 'cliente' : Cliente }))],
      ['query'],
    ),
  'getRodape' : IDL.Func([], [IDL.Opt(Rodape)], ['query']),
  'getTabelaPreco' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TabelaPrecoCategoria)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'inserirArtigoAbaixo' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'inserirArtigoAcima' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'inserirLinhaAbaixo' : IDL.Func(
      [IDL.Text, IDL.Nat, TabelaPrecoLinha],
      [],
      [],
    ),
  'inserirLinhaAcima' : IDL.Func([IDL.Text, IDL.Nat, TabelaPrecoLinha], [], []),
  'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'listarBackups' : IDL.Func([], [IDL.Vec(BackupInfo)], ['query']),
  'listarClientes' : IDL.Func([], [IDL.Vec(Cliente)], ['query']),
  'listarGestores' : IDL.Func([], [IDL.Vec(Gestor)], ['query']),
  'listarMateriais' : IDL.Func([], [IDL.Vec(Material)], ['query']),
  'listarMateriaisComMenorPreco' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'nome' : IDL.Text,
            'menorPreco' : IDL.Opt(PrecoFornecedor),
          })
        ),
      ],
      ['query'],
    ),
  'listarOrcamentos' : IDL.Func([], [IDL.Vec(Orcamento)], ['query']),
  'listarPorGestor' : IDL.Func([IDL.Text], [IDL.Vec(Encomenda)], ['query']),
  'listarPorStatus' : IDL.Func([Status], [IDL.Vec(Encomenda)], ['query']),
  'listarTabelasPreco' : IDL.Func(
      [],
      [IDL.Vec(TabelaPrecoCategoria)],
      ['query'],
    ),
  'moverArtigoParaBaixo' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'moverArtigoParaCima' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'moverParaStatusAnterior' : IDL.Func([IDL.Nat], [], []),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removerGestor' : IDL.Func([IDL.Text], [], []),
  'restaurarBackup' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'mensagem' : IDL.Text })],
      [],
    ),
  'salvarDadosCompletos' : IDL.Func(
      [DadosCompletos],
      [IDL.Record({ 'mensagem' : IDL.Text })],
      [],
    ),
  'salvarEmpresa' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'salvarRodape' : IDL.Func([IDL.Text], [], []),
  'salvarTabelaPreco' : IDL.Func(
      [IDL.Text, IDL.Vec(TabelaPrecoLinha), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'verificarGestores' : IDL.Func([], [IDL.Bool], ['query']),
  'waitForAutosave' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TabelaPrecoLinha = IDL.Record({
    'descricao' : IDL.Text,
    'colunas' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ItemOrcamento = IDL.Record({
    'nomeMaterial' : IDL.Text,
    'descricao' : IDL.Text,
    'precoUnitario' : IDL.Nat,
    'quantidade' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const Cliente = IDL.Record({
    'id' : IDL.Nat,
    'nif' : IDL.Text,
    'contato' : IDL.Text,
    'nome' : IDL.Text,
    'morada' : IDL.Text,
  });
  const PrecoFornecedor = IDL.Record({
    'fornecedor' : IDL.Text,
    'data' : IDL.Int,
    'vendedor' : IDL.Text,
    'contatoVendedor' : IDL.Text,
    'preco' : IDL.Nat,
  });
  const Material = IDL.Record({
    'id' : IDL.Nat,
    'nome' : IDL.Text,
    'precos' : IDL.Vec(PrecoFornecedor),
  });
  const StatusOrcamento = IDL.Variant({
    'aceito' : IDL.Null,
    'pendente' : IDL.Null,
    'rejeitado' : IDL.Null,
  });
  const Empresa = IDL.Record({
    'cae' : IDL.Text,
    'nib' : IDL.Text,
    'alvara' : IDL.Text,
    'nome' : IDL.Text,
    'email' : IDL.Text,
    'logoPath' : IDL.Text,
    'morada' : IDL.Text,
    'telefone' : IDL.Text,
  });
  const Orcamento = IDL.Record({
    'id' : IDL.Nat,
    'iva' : IDL.Nat,
    'desconto' : IDL.Nat,
    'status' : StatusOrcamento,
    'condicoesFornecimento' : IDL.Text,
    'imagemAdicionalPath' : IDL.Opt(IDL.Text),
    'validadeOrcamento' : IDL.Text,
    'observacoes' : IDL.Text,
    'gestor' : IDL.Text,
    'itens' : IDL.Vec(ItemOrcamento),
    'empresa' : Empresa,
    'clienteId' : IDL.Nat,
    'dataOrcamento' : IDL.Int,
    'valorTotal' : IDL.Nat,
  });
  const Status = IDL.Variant({
    'encomenda' : IDL.Null,
    'concluido' : IDL.Null,
    'montagem' : IDL.Null,
    'producao' : IDL.Null,
    'porPagar' : IDL.Null,
  });
  const Encomenda = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'contato' : IDL.Text,
    'descricao' : IDL.Text,
    'dataCriacao' : IDL.Int,
    'gestor' : IDL.Text,
    'valorAdiantado' : IDL.Nat,
    'nomeCliente' : IDL.Text,
    'valorTotal' : IDL.Nat,
  });
  const RelatorioPDF = IDL.Record({
    'gestor' : IDL.Text,
    'encomendas' : IDL.Vec(Encomenda),
  });
  const ResumoFinanceiro = IDL.Record({
    'totalValor' : IDL.Nat,
    'totalEncomendas' : IDL.Nat,
    'totalPendente' : IDL.Nat,
    'totalAdiantado' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Movimentacao = IDL.Record({
    'statusAnterior' : Status,
    'timestamp' : IDL.Int,
    'novoStatus' : Status,
  });
  const Gestor = IDL.Record({ 'nome' : IDL.Text });
  const TabelaPrecoCategoria = IDL.Record({
    'categoria' : IDL.Text,
    'titulosColunas' : IDL.Vec(IDL.Text),
    'linhas' : IDL.Vec(TabelaPrecoLinha),
  });
  const Rodape = IDL.Record({ 'textoCompleto' : IDL.Text });
  const DadosCompletos = IDL.Record({
    'clientes' : IDL.Vec(Cliente),
    'lastEditTime' : IDL.Int,
    'orcamentos' : IDL.Vec(Orcamento),
    'historico' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(Movimentacao))),
    'nextId' : IDL.Nat,
    'gestores' : IDL.Vec(Gestor),
    'materiais' : IDL.Vec(Material),
    'encomendas' : IDL.Vec(Encomenda),
    'tabelasPreco' : IDL.Vec(TabelaPrecoCategoria),
    'nextOrcamentoId' : IDL.Nat,
    'rodape' : IDL.Opt(Rodape),
    'nextMaterialId' : IDL.Nat,
    'empresa' : IDL.Opt(Empresa),
    'nextClienteId' : IDL.Nat,
    'backups' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const BackupInfo = IDL.Record({
    'id' : IDL.Nat,
    'descricao' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'aceitarOrcamento' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'mensagem' : IDL.Text,
            'encomendaId' : IDL.Opt(IDL.Nat),
            'sucesso' : IDL.Bool,
          }),
        ],
        [],
      ),
    'adicionarGestor' : IDL.Func([IDL.Text], [], []),
    'adicionarLinhaTabela' : IDL.Func([IDL.Text, TabelaPrecoLinha], [], []),
    'adicionarMaterial' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adicionarPrecoFornecedor' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'atualizarEmpresa' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'atualizarLinhaTabela' : IDL.Func(
        [IDL.Text, TabelaPrecoLinha, IDL.Nat],
        [],
        [],
      ),
    'atualizarRodape' : IDL.Func([IDL.Text], [], []),
    'atualizarStatus' : IDL.Func([IDL.Nat], [], []),
    'atualizarTituloColuna' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'criarBackup' : IDL.Func(
        [],
        [IDL.Record({ 'backupId' : IDL.Nat, 'mensagem' : IDL.Text })],
        [],
      ),
    'criarCliente' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'criarEncomenda' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'criarOrcamento' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Vec(ItemOrcamento),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'deletarCliente' : IDL.Func([IDL.Nat], [], []),
    'deletarEncomenda' : IDL.Func([IDL.Nat], [], []),
    'deletarItemOrcamento' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'deletarMaterial' : IDL.Func([IDL.Nat], [], []),
    'deletarOrcamento' : IDL.Func([IDL.Nat], [], []),
    'deletarPrecoFornecedor' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'editarCliente' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'editarEncomenda' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'editarMaterial' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'editarOrcamento' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(ItemOrcamento),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'editarPrecoFornecedor' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'eliminarBackup' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'mensagem' : IDL.Text })],
        [],
      ),
    'eliminarLinha' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'filtrarClientesPorNome' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Cliente)],
        ['query'],
      ),
    'filtrarMateriaisPorFornecedor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Material)],
        ['query'],
      ),
    'filtrarMateriaisPorNome' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Material)],
        ['query'],
      ),
    'filtrarOrcamentosPorGestor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Orcamento)],
        ['query'],
      ),
    'filtrarOrcamentosPorGestorENomeCliente' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Orcamento)],
        ['query'],
      ),
    'filtrarOrcamentosPorNomeCliente' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Orcamento)],
        ['query'],
      ),
    'filtrarPorGestorEStatus' : IDL.Func(
        [IDL.Text, Status],
        [IDL.Vec(Encomenda)],
        ['query'],
      ),
    'gerarRelatorioPDF' : IDL.Func(
        [Status, IDL.Opt(IDL.Text)],
        [
          IDL.Record({
            'relatorios' : IDL.Vec(RelatorioPDF),
            'resumoFinanceiro' : ResumoFinanceiro,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCliente' : IDL.Func([IDL.Nat], [IDL.Opt(Cliente)], ['query']),
    'getDadosCompletos' : IDL.Func([], [DadosCompletos], []),
    'getDadosOrcamentoPDF' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'rodape' : IDL.Opt(Rodape),
              'empresa' : Empresa,
              'orcamento' : Orcamento,
              'imagemAdicional' : IDL.Opt(FileReference),
              'cliente' : Cliente,
            })
          ),
        ],
        ['query'],
      ),
    'getEmpresa' : IDL.Func([], [IDL.Opt(Empresa)], ['query']),
    'getEncomenda' : IDL.Func([IDL.Nat], [IDL.Opt(Encomenda)], ['query']),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getHistorico' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(Movimentacao))],
        ['query'],
      ),
    'getMaterial' : IDL.Func([IDL.Nat], [IDL.Opt(Material)], ['query']),
    'getOrcamento' : IDL.Func([IDL.Nat], [IDL.Opt(Orcamento)], ['query']),
    'getOrcamentoCompleto' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Record({ 'orcamento' : Orcamento, 'cliente' : Cliente }))],
        ['query'],
      ),
    'getRodape' : IDL.Func([], [IDL.Opt(Rodape)], ['query']),
    'getTabelaPreco' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TabelaPrecoCategoria)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'inserirArtigoAbaixo' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'inserirArtigoAcima' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'inserirLinhaAbaixo' : IDL.Func(
        [IDL.Text, IDL.Nat, TabelaPrecoLinha],
        [],
        [],
      ),
    'inserirLinhaAcima' : IDL.Func(
        [IDL.Text, IDL.Nat, TabelaPrecoLinha],
        [],
        [],
      ),
    'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'listarBackups' : IDL.Func([], [IDL.Vec(BackupInfo)], ['query']),
    'listarClientes' : IDL.Func([], [IDL.Vec(Cliente)], ['query']),
    'listarGestores' : IDL.Func([], [IDL.Vec(Gestor)], ['query']),
    'listarMateriais' : IDL.Func([], [IDL.Vec(Material)], ['query']),
    'listarMateriaisComMenorPreco' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'nome' : IDL.Text,
              'menorPreco' : IDL.Opt(PrecoFornecedor),
            })
          ),
        ],
        ['query'],
      ),
    'listarOrcamentos' : IDL.Func([], [IDL.Vec(Orcamento)], ['query']),
    'listarPorGestor' : IDL.Func([IDL.Text], [IDL.Vec(Encomenda)], ['query']),
    'listarPorStatus' : IDL.Func([Status], [IDL.Vec(Encomenda)], ['query']),
    'listarTabelasPreco' : IDL.Func(
        [],
        [IDL.Vec(TabelaPrecoCategoria)],
        ['query'],
      ),
    'moverArtigoParaBaixo' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'moverArtigoParaCima' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'moverParaStatusAnterior' : IDL.Func([IDL.Nat], [], []),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removerGestor' : IDL.Func([IDL.Text], [], []),
    'restaurarBackup' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'mensagem' : IDL.Text })],
        [],
      ),
    'salvarDadosCompletos' : IDL.Func(
        [DadosCompletos],
        [IDL.Record({ 'mensagem' : IDL.Text })],
        [],
      ),
    'salvarEmpresa' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'salvarRodape' : IDL.Func([IDL.Text], [], []),
    'salvarTabelaPreco' : IDL.Func(
        [IDL.Text, IDL.Vec(TabelaPrecoLinha), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'verificarGestores' : IDL.Func([], [IDL.Bool], ['query']),
    'waitForAutosave' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };