/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackupInfo {
  'id' : bigint,
  'descricao' : string,
  'timestamp' : bigint,
}
export interface Cliente {
  'id' : bigint,
  'nif' : string,
  'contato' : string,
  'nome' : string,
  'morada' : string,
}
export interface DadosCompletos {
  'clientes' : Array<Cliente>,
  'lastEditTime' : bigint,
  'orcamentos' : Array<Orcamento>,
  'historico' : Array<[bigint, Array<Movimentacao>]>,
  'nextId' : bigint,
  'gestores' : Array<Gestor>,
  'materiais' : Array<Material>,
  'encomendas' : Array<Encomenda>,
  'tabelasPreco' : Array<TabelaPrecoCategoria>,
  'nextOrcamentoId' : bigint,
  'rodape' : [] | [Rodape],
  'nextMaterialId' : bigint,
  'empresa' : [] | [Empresa],
  'nextClienteId' : bigint,
  'backups' : Array<[bigint, string]>,
}
export interface Empresa {
  'cae' : string,
  'nib' : string,
  'alvara' : string,
  'nome' : string,
  'email' : string,
  'logoPath' : string,
  'morada' : string,
  'telefone' : string,
}
export interface Encomenda {
  'id' : bigint,
  'status' : Status,
  'contato' : string,
  'descricao' : string,
  'dataCriacao' : bigint,
  'gestor' : string,
  'valorAdiantado' : bigint,
  'nomeCliente' : string,
  'valorTotal' : bigint,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface Gestor { 'nome' : string }
export interface ItemOrcamento {
  'nomeMaterial' : string,
  'descricao' : string,
  'precoUnitario' : bigint,
  'quantidade' : bigint,
  'subtotal' : bigint,
}
export interface Material {
  'id' : bigint,
  'nome' : string,
  'precos' : Array<PrecoFornecedor>,
}
export interface Movimentacao {
  'statusAnterior' : Status,
  'timestamp' : bigint,
  'novoStatus' : Status,
}
export interface Orcamento {
  'id' : bigint,
  'iva' : bigint,
  'desconto' : bigint,
  'status' : StatusOrcamento,
  'condicoesFornecimento' : string,
  'imagemAdicionalPath' : [] | [string],
  'validadeOrcamento' : string,
  'observacoes' : string,
  'gestor' : string,
  'itens' : Array<ItemOrcamento>,
  'empresa' : Empresa,
  'clienteId' : bigint,
  'dataOrcamento' : bigint,
  'valorTotal' : bigint,
}
export interface PrecoFornecedor {
  'fornecedor' : string,
  'data' : bigint,
  'vendedor' : string,
  'contatoVendedor' : string,
  'preco' : bigint,
}
export interface RelatorioPDF {
  'gestor' : string,
  'encomendas' : Array<Encomenda>,
}
export interface ResumoFinanceiro {
  'totalValor' : bigint,
  'totalEncomendas' : bigint,
  'totalPendente' : bigint,
  'totalAdiantado' : bigint,
}
export interface Rodape { 'textoCompleto' : string }
export type Status = { 'encomenda' : null } |
  { 'concluido' : null } |
  { 'montagem' : null } |
  { 'producao' : null } |
  { 'porPagar' : null };
export type StatusOrcamento = { 'aceito' : null } |
  { 'pendente' : null } |
  { 'rejeitado' : null };
export interface TabelaPrecoCategoria {
  'categoria' : string,
  'titulosColunas' : Array<string>,
  'linhas' : Array<TabelaPrecoLinha>,
}
export interface TabelaPrecoLinha {
  'descricao' : string,
  'colunas' : Array<string>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'aceitarOrcamento' : ActorMethod<
    [bigint],
    { 'mensagem' : string, 'encomendaId' : [] | [bigint], 'sucesso' : boolean }
  >,
  'adicionarGestor' : ActorMethod<[string], undefined>,
  'adicionarLinhaTabela' : ActorMethod<[string, TabelaPrecoLinha], undefined>,
  'adicionarMaterial' : ActorMethod<
    [string, bigint, string, string, string],
    bigint
  >,
  'adicionarPrecoFornecedor' : ActorMethod<
    [bigint, bigint, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'atualizarEmpresa' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
  'atualizarLinhaTabela' : ActorMethod<
    [string, TabelaPrecoLinha, bigint],
    undefined
  >,
  'atualizarRodape' : ActorMethod<[string], undefined>,
  'atualizarStatus' : ActorMethod<[bigint], undefined>,
  'atualizarTituloColuna' : ActorMethod<[string, string, bigint], undefined>,
  'criarBackup' : ActorMethod<[], { 'backupId' : bigint, 'mensagem' : string }>,
  'criarCliente' : ActorMethod<[string, string, string, string], bigint>,
  'criarEncomenda' : ActorMethod<
    [string, string, string, string, bigint, bigint],
    bigint
  >,
  'criarOrcamento' : ActorMethod<
    [
      bigint,
      string,
      Array<ItemOrcamento>,
      string,
      string,
      string,
      [] | [string],
      bigint,
      bigint,
    ],
    bigint
  >,
  'deletarCliente' : ActorMethod<[bigint], undefined>,
  'deletarEncomenda' : ActorMethod<[bigint], undefined>,
  'deletarItemOrcamento' : ActorMethod<[bigint, bigint], undefined>,
  'deletarMaterial' : ActorMethod<[bigint], undefined>,
  'deletarOrcamento' : ActorMethod<[bigint], undefined>,
  'deletarPrecoFornecedor' : ActorMethod<[bigint, bigint], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'editarCliente' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'editarEncomenda' : ActorMethod<
    [bigint, string, string, string, string, bigint, bigint],
    undefined
  >,
  'editarMaterial' : ActorMethod<[bigint, string], undefined>,
  'editarOrcamento' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      Array<ItemOrcamento>,
      string,
      string,
      string,
      [] | [string],
      bigint,
      bigint,
    ],
    undefined
  >,
  'editarPrecoFornecedor' : ActorMethod<
    [bigint, bigint, bigint, string, string, string],
    undefined
  >,
  'eliminarBackup' : ActorMethod<[bigint], { 'mensagem' : string }>,
  'eliminarLinha' : ActorMethod<[string, bigint], undefined>,
  'filtrarClientesPorNome' : ActorMethod<[string], Array<Cliente>>,
  'filtrarMateriaisPorFornecedor' : ActorMethod<[string], Array<Material>>,
  'filtrarMateriaisPorNome' : ActorMethod<[string], Array<Material>>,
  'filtrarOrcamentosPorGestor' : ActorMethod<[string], Array<Orcamento>>,
  'filtrarOrcamentosPorGestorENomeCliente' : ActorMethod<
    [string, string],
    Array<Orcamento>
  >,
  'filtrarOrcamentosPorNomeCliente' : ActorMethod<[string], Array<Orcamento>>,
  'filtrarPorGestorEStatus' : ActorMethod<[string, Status], Array<Encomenda>>,
  'gerarRelatorioPDF' : ActorMethod<
    [Status, [] | [string]],
    {
      'relatorios' : Array<RelatorioPDF>,
      'resumoFinanceiro' : ResumoFinanceiro,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCliente' : ActorMethod<[bigint], [] | [Cliente]>,
  'getDadosCompletos' : ActorMethod<[], DadosCompletos>,
  'getDadosOrcamentoPDF' : ActorMethod<
    [bigint],
    [] | [
      {
        'rodape' : [] | [Rodape],
        'empresa' : Empresa,
        'orcamento' : Orcamento,
        'imagemAdicional' : [] | [FileReference],
        'cliente' : Cliente,
      }
    ]
  >,
  'getEmpresa' : ActorMethod<[], [] | [Empresa]>,
  'getEncomenda' : ActorMethod<[bigint], [] | [Encomenda]>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getHistorico' : ActorMethod<[bigint], [] | [Array<Movimentacao>]>,
  'getMaterial' : ActorMethod<[bigint], [] | [Material]>,
  'getOrcamento' : ActorMethod<[bigint], [] | [Orcamento]>,
  'getOrcamentoCompleto' : ActorMethod<
    [bigint],
    [] | [{ 'orcamento' : Orcamento, 'cliente' : Cliente }]
  >,
  'getRodape' : ActorMethod<[], [] | [Rodape]>,
  'getTabelaPreco' : ActorMethod<[string], [] | [TabelaPrecoCategoria]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'inserirArtigoAbaixo' : ActorMethod<[bigint, bigint], undefined>,
  'inserirArtigoAcima' : ActorMethod<[bigint, bigint], undefined>,
  'inserirLinhaAbaixo' : ActorMethod<
    [string, bigint, TabelaPrecoLinha],
    undefined
  >,
  'inserirLinhaAcima' : ActorMethod<
    [string, bigint, TabelaPrecoLinha],
    undefined
  >,
  'isAuthenticated' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'listarBackups' : ActorMethod<[], Array<BackupInfo>>,
  'listarClientes' : ActorMethod<[], Array<Cliente>>,
  'listarGestores' : ActorMethod<[], Array<Gestor>>,
  'listarMateriais' : ActorMethod<[], Array<Material>>,
  'listarMateriaisComMenorPreco' : ActorMethod<
    [],
    Array<
      { 'id' : bigint, 'nome' : string, 'menorPreco' : [] | [PrecoFornecedor] }
    >
  >,
  'listarOrcamentos' : ActorMethod<[], Array<Orcamento>>,
  'listarPorGestor' : ActorMethod<[string], Array<Encomenda>>,
  'listarPorStatus' : ActorMethod<[Status], Array<Encomenda>>,
  'listarTabelasPreco' : ActorMethod<[], Array<TabelaPrecoCategoria>>,
  'moverArtigoParaBaixo' : ActorMethod<[bigint, bigint], undefined>,
  'moverArtigoParaCima' : ActorMethod<[bigint, bigint], undefined>,
  'moverParaStatusAnterior' : ActorMethod<[bigint], undefined>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'removerGestor' : ActorMethod<[string], undefined>,
  'restaurarBackup' : ActorMethod<[bigint], { 'mensagem' : string }>,
  'salvarDadosCompletos' : ActorMethod<
    [DadosCompletos],
    { 'mensagem' : string }
  >,
  'salvarEmpresa' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
  'salvarRodape' : ActorMethod<[string], undefined>,
  'salvarTabelaPreco' : ActorMethod<
    [string, Array<TabelaPrecoLinha>, Array<string>],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'verificarGestores' : ActorMethod<[], boolean>,
  'waitForAutosave' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];