/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Cliente {
    id: bigint;
    nif: string;
    contato: string;
    nome: string;
    morada: string;
}
export interface Rodape {
    textoCompleto: string;
}
export interface PrecoFornecedor {
    fornecedor: string;
    data: bigint;
    vendedor: string;
    contatoVendedor: string;
    preco: bigint;
}
export interface DadosCompletos {
    clientes: Array<Cliente>;
    lastEditTime: bigint;
    orcamentos: Array<Orcamento>;
    historico: Array<[bigint, Array<Movimentacao>]>;
    nextId: bigint;
    gestores: Array<Gestor>;
    materiais: Array<Material>;
    encomendas: Array<Encomenda>;
    tabelasPreco: Array<TabelaPrecoCategoria>;
    nextOrcamentoId: bigint;
    rodape?: Rodape;
    nextMaterialId: bigint;
    empresa?: Empresa;
    nextClienteId: bigint;
    backups: Array<[bigint, string]>;
}
export interface Gestor {
    nome: string;
}
export interface Encomenda {
    id: bigint;
    status: Status;
    contato: string;
    descricao: string;
    dataCriacao: bigint;
    gestor: string;
    valorAdiantado: bigint;
    nomeCliente: string;
    valorTotal: bigint;
}
export interface Empresa {
    cae: string;
    nib: string;
    alvara: string;
    nome: string;
    email: string;
    logoPath: string;
    morada: string;
    telefone: string;
}
export interface ItemOrcamento {
    nomeMaterial: string;
    descricao: string;
    precoUnitario: bigint;
    quantidade: bigint;
    subtotal: bigint;
}
export interface BackupInfo {
    id: bigint;
    descricao: string;
    timestamp: bigint;
}
export interface TabelaPrecoCategoria {
    categoria: string;
    titulosColunas: Array<string>;
    linhas: Array<TabelaPrecoLinha>;
}
export interface TabelaPrecoLinha {
    descricao: string;
    colunas: Array<string>;
}
export interface ResumoFinanceiro {
    totalValor: bigint;
    totalEncomendas: bigint;
    totalPendente: bigint;
    totalAdiantado: bigint;
}
export interface Movimentacao {
    statusAnterior: Status;
    timestamp: bigint;
    novoStatus: Status;
}
export interface Material {
    id: bigint;
    nome: string;
    precos: Array<PrecoFornecedor>;
}
export interface RelatorioPDF {
    gestor: string;
    encomendas: Array<Encomenda>;
}
export interface Orcamento {
    id: bigint;
    iva: bigint;
    desconto: bigint;
    status: StatusOrcamento;
    condicoesFornecimento: string;
    imagemAdicionalPath?: string;
    validadeOrcamento: string;
    observacoes: string;
    gestor: string;
    itens: Array<ItemOrcamento>;
    empresa: Empresa;
    clienteId: bigint;
    dataOrcamento: bigint;
    valorTotal: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface FileReference {
    hash: string;
    path: string;
}
export enum Status {
    encomenda = "encomenda",
    concluido = "concluido",
    montagem = "montagem",
    producao = "producao",
    porPagar = "porPagar"
}
export enum StatusOrcamento {
    aceito = "aceito",
    pendente = "pendente",
    rejeitado = "rejeitado"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    aceitarOrcamento(id: bigint): Promise<{
        mensagem: string;
        encomendaId?: bigint;
        sucesso: boolean;
    }>;
    adicionarGestor(nome: string): Promise<void>;
    adicionarLinhaTabela(categoria: string, novaLinha: TabelaPrecoLinha): Promise<void>;
    adicionarMaterial(nome: string, preco: bigint, fornecedor: string, vendedor: string, contatoVendedor: string): Promise<bigint>;
    adicionarPrecoFornecedor(materialId: bigint, preco: bigint, fornecedor: string, vendedor: string, contatoVendedor: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    atualizarEmpresa(nome: string, morada: string, nib: string, cae: string, alvara: string, telefone: string, email: string, logoPath: string): Promise<void>;
    atualizarLinhaTabela(categoria: string, linhaAtualizada: TabelaPrecoLinha, linhaIndex: bigint): Promise<void>;
    atualizarRodape(textoCompleto: string): Promise<void>;
    atualizarStatus(id: bigint): Promise<void>;
    atualizarTituloColuna(categoria: string, novoTitulo: string, colunaIndex: bigint): Promise<void>;
    criarBackup(): Promise<{
        backupId: bigint;
        mensagem: string;
    }>;
    criarCliente(nome: string, contato: string, morada: string, nif: string): Promise<bigint>;
    criarEncomenda(nomeCliente: string, descricao: string, contato: string, gestor: string, valorTotal: bigint, valorAdiantado: bigint): Promise<bigint>;
    criarOrcamento(clienteId: bigint, gestor: string, itens: Array<ItemOrcamento>, observacoes: string, condicoesFornecimento: string, validadeOrcamento: string, imagemAdicionalPath: string | null, iva: bigint, desconto: bigint): Promise<bigint>;
    deletarCliente(id: bigint): Promise<void>;
    deletarEncomenda(id: bigint): Promise<void>;
    deletarItemOrcamento(orcamentoId: bigint, itemIndex: bigint): Promise<void>;
    deletarMaterial(id: bigint): Promise<void>;
    deletarOrcamento(id: bigint): Promise<void>;
    deletarPrecoFornecedor(materialId: bigint, index: bigint): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    editarCliente(id: bigint, nome: string, contato: string, morada: string, nif: string): Promise<void>;
    editarEncomenda(id: bigint, nomeCliente: string, descricao: string, contato: string, gestor: string, valorTotal: bigint, valorAdiantado: bigint): Promise<void>;
    editarMaterial(id: bigint, nome: string): Promise<void>;
    editarOrcamento(id: bigint, clienteId: bigint, gestor: string, itens: Array<ItemOrcamento>, observacoes: string, condicoesFornecimento: string, validadeOrcamento: string, imagemAdicionalPath: string | null, iva: bigint, desconto: bigint): Promise<void>;
    editarPrecoFornecedor(materialId: bigint, index: bigint, preco: bigint, fornecedor: string, vendedor: string, contatoVendedor: string): Promise<void>;
    eliminarBackup(id: bigint): Promise<{
        mensagem: string;
    }>;
    eliminarLinha(categoria: string, linhaIndex: bigint): Promise<void>;
    filtrarClientesPorNome(nome: string): Promise<Array<Cliente>>;
    filtrarMateriaisPorFornecedor(fornecedor: string): Promise<Array<Material>>;
    filtrarMateriaisPorNome(nome: string): Promise<Array<Material>>;
    filtrarOrcamentosPorGestor(gestor: string): Promise<Array<Orcamento>>;
    filtrarOrcamentosPorGestorENomeCliente(gestor: string, nomeCliente: string): Promise<Array<Orcamento>>;
    filtrarOrcamentosPorNomeCliente(nomeCliente: string): Promise<Array<Orcamento>>;
    filtrarPorGestorEStatus(gestor: string, status: Status): Promise<Array<Encomenda>>;
    gerarRelatorioPDF(status: Status, gestorFilter: string | null): Promise<{
        relatorios: Array<RelatorioPDF>;
        resumoFinanceiro: ResumoFinanceiro;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCliente(id: bigint): Promise<Cliente | null>;
    getDadosCompletos(): Promise<DadosCompletos>;
    getDadosOrcamentoPDF(id: bigint): Promise<{
        rodape?: Rodape;
        empresa: Empresa;
        orcamento: Orcamento;
        imagemAdicional?: FileReference;
        cliente: Cliente;
    } | null>;
    getEmpresa(): Promise<Empresa | null>;
    getEncomenda(id: bigint): Promise<Encomenda | null>;
    getFileReference(path: string): Promise<FileReference>;
    getHistorico(id: bigint): Promise<Array<Movimentacao> | null>;
    getMaterial(id: bigint): Promise<Material | null>;
    getOrcamento(id: bigint): Promise<Orcamento | null>;
    getOrcamentoCompleto(id: bigint): Promise<{
        orcamento: Orcamento;
        cliente: Cliente;
    } | null>;
    getRodape(): Promise<Rodape | null>;
    getTabelaPreco(categoria: string): Promise<TabelaPrecoCategoria | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    inserirArtigoAbaixo(orcamentoId: bigint, artigoIndex: bigint): Promise<void>;
    inserirArtigoAcima(orcamentoId: bigint, artigoIndex: bigint): Promise<void>;
    inserirLinhaAbaixo(categoria: string, linhaIndex: bigint, novaLinha: TabelaPrecoLinha): Promise<void>;
    inserirLinhaAcima(categoria: string, linhaIndex: bigint, novaLinha: TabelaPrecoLinha): Promise<void>;
    isAuthenticated(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listFileReferences(): Promise<Array<FileReference>>;
    listarBackups(): Promise<Array<BackupInfo>>;
    listarClientes(): Promise<Array<Cliente>>;
    listarGestores(): Promise<Array<Gestor>>;
    listarMateriais(): Promise<Array<Material>>;
    listarMateriaisComMenorPreco(): Promise<Array<{
        id: bigint;
        nome: string;
        menorPreco?: PrecoFornecedor;
    }>>;
    listarOrcamentos(): Promise<Array<Orcamento>>;
    listarPorGestor(gestor: string): Promise<Array<Encomenda>>;
    listarPorStatus(status: Status): Promise<Array<Encomenda>>;
    listarTabelasPreco(): Promise<Array<TabelaPrecoCategoria>>;
    moverArtigoParaBaixo(orcamentoId: bigint, artigoIndex: bigint): Promise<void>;
    moverArtigoParaCima(orcamentoId: bigint, artigoIndex: bigint): Promise<void>;
    moverParaStatusAnterior(id: bigint): Promise<void>;
    registerFileReference(path: string, hash: string): Promise<void>;
    removerGestor(nome: string): Promise<void>;
    restaurarBackup(id: bigint): Promise<{
        mensagem: string;
    }>;
    salvarDadosCompletos(dados: DadosCompletos): Promise<{
        mensagem: string;
    }>;
    salvarEmpresa(nome: string, morada: string, nib: string, cae: string, alvara: string, telefone: string, email: string, logoPath: string): Promise<void>;
    salvarRodape(textoCompleto: string): Promise<void>;
    salvarTabelaPreco(categoria: string, linhas: Array<TabelaPrecoLinha>, titulosColunas: Array<string>): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    verificarGestores(): Promise<boolean>;
    waitForAutosave(): Promise<void>;
}
import type { Cliente as _Cliente, DadosCompletos as _DadosCompletos, Empresa as _Empresa, Encomenda as _Encomenda, FileReference as _FileReference, Gestor as _Gestor, ItemOrcamento as _ItemOrcamento, Material as _Material, Movimentacao as _Movimentacao, Orcamento as _Orcamento, PrecoFornecedor as _PrecoFornecedor, RelatorioPDF as _RelatorioPDF, ResumoFinanceiro as _ResumoFinanceiro, Rodape as _Rodape, Status as _Status, StatusOrcamento as _StatusOrcamento, TabelaPrecoCategoria as _TabelaPrecoCategoria, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async aceitarOrcamento(arg0: bigint): Promise<{
        mensagem: string;
        encomendaId?: bigint;
        sucesso: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.aceitarOrcamento(arg0);
                return from_candid_record_n1(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.aceitarOrcamento(arg0);
            return from_candid_record_n1(this.uploadFile, this.downloadFile, result);
        }
    }
    async adicionarGestor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adicionarGestor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adicionarGestor(arg0);
            return result;
        }
    }
    async adicionarLinhaTabela(arg0: string, arg1: TabelaPrecoLinha): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adicionarLinhaTabela(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adicionarLinhaTabela(arg0, arg1);
            return result;
        }
    }
    async adicionarMaterial(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adicionarMaterial(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adicionarMaterial(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async adicionarPrecoFornecedor(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adicionarPrecoFornecedor(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adicionarPrecoFornecedor(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async atualizarEmpresa(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.atualizarEmpresa(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.atualizarEmpresa(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async atualizarLinhaTabela(arg0: string, arg1: TabelaPrecoLinha, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.atualizarLinhaTabela(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.atualizarLinhaTabela(arg0, arg1, arg2);
            return result;
        }
    }
    async atualizarRodape(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.atualizarRodape(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.atualizarRodape(arg0);
            return result;
        }
    }
    async atualizarStatus(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.atualizarStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.atualizarStatus(arg0);
            return result;
        }
    }
    async atualizarTituloColuna(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.atualizarTituloColuna(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.atualizarTituloColuna(arg0, arg1, arg2);
            return result;
        }
    }
    async criarBackup(): Promise<{
        backupId: bigint;
        mensagem: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.criarBackup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.criarBackup();
            return result;
        }
    }
    async criarCliente(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.criarCliente(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.criarCliente(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async criarEncomenda(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.criarEncomenda(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.criarEncomenda(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async criarOrcamento(arg0: bigint, arg1: string, arg2: Array<ItemOrcamento>, arg3: string, arg4: string, arg5: string, arg6: string | null, arg7: bigint, arg8: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.criarOrcamento(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n5(this.uploadFile, this.downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.criarOrcamento(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n5(this.uploadFile, this.downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
    async deletarCliente(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletarCliente(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletarCliente(arg0);
            return result;
        }
    }
    async deletarEncomenda(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletarEncomenda(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletarEncomenda(arg0);
            return result;
        }
    }
    async deletarItemOrcamento(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletarItemOrcamento(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletarItemOrcamento(arg0, arg1);
            return result;
        }
    }
    async deletarMaterial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletarMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletarMaterial(arg0);
            return result;
        }
    }
    async deletarOrcamento(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletarOrcamento(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletarOrcamento(arg0);
            return result;
        }
    }
    async deletarPrecoFornecedor(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletarPrecoFornecedor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletarPrecoFornecedor(arg0, arg1);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async editarCliente(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editarCliente(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editarCliente(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async editarEncomenda(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editarEncomenda(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editarEncomenda(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async editarMaterial(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editarMaterial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editarMaterial(arg0, arg1);
            return result;
        }
    }
    async editarOrcamento(arg0: bigint, arg1: bigint, arg2: string, arg3: Array<ItemOrcamento>, arg4: string, arg5: string, arg6: string, arg7: string | null, arg8: bigint, arg9: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editarOrcamento(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n5(this.uploadFile, this.downloadFile, arg7), arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editarOrcamento(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n5(this.uploadFile, this.downloadFile, arg7), arg8, arg9);
            return result;
        }
    }
    async editarPrecoFornecedor(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editarPrecoFornecedor(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editarPrecoFornecedor(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async eliminarBackup(arg0: bigint): Promise<{
        mensagem: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.eliminarBackup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.eliminarBackup(arg0);
            return result;
        }
    }
    async eliminarLinha(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.eliminarLinha(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.eliminarLinha(arg0, arg1);
            return result;
        }
    }
    async filtrarClientesPorNome(arg0: string): Promise<Array<Cliente>> {
        if (this.processError) {
            try {
                const result = await this.actor.filtrarClientesPorNome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filtrarClientesPorNome(arg0);
            return result;
        }
    }
    async filtrarMateriaisPorFornecedor(arg0: string): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.filtrarMateriaisPorFornecedor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filtrarMateriaisPorFornecedor(arg0);
            return result;
        }
    }
    async filtrarMateriaisPorNome(arg0: string): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.filtrarMateriaisPorNome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filtrarMateriaisPorNome(arg0);
            return result;
        }
    }
    async filtrarOrcamentosPorGestor(arg0: string): Promise<Array<Orcamento>> {
        if (this.processError) {
            try {
                const result = await this.actor.filtrarOrcamentosPorGestor(arg0);
                return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filtrarOrcamentosPorGestor(arg0);
            return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async filtrarOrcamentosPorGestorENomeCliente(arg0: string, arg1: string): Promise<Array<Orcamento>> {
        if (this.processError) {
            try {
                const result = await this.actor.filtrarOrcamentosPorGestorENomeCliente(arg0, arg1);
                return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filtrarOrcamentosPorGestorENomeCliente(arg0, arg1);
            return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async filtrarOrcamentosPorNomeCliente(arg0: string): Promise<Array<Orcamento>> {
        if (this.processError) {
            try {
                const result = await this.actor.filtrarOrcamentosPorNomeCliente(arg0);
                return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filtrarOrcamentosPorNomeCliente(arg0);
            return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async filtrarPorGestorEStatus(arg0: string, arg1: Status): Promise<Array<Encomenda>> {
        if (this.processError) {
            try {
                const result = await this.actor.filtrarPorGestorEStatus(arg0, to_candid_Status_n12(this.uploadFile, this.downloadFile, arg1));
                return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filtrarPorGestorEStatus(arg0, to_candid_Status_n12(this.uploadFile, this.downloadFile, arg1));
            return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async gerarRelatorioPDF(arg0: Status, arg1: string | null): Promise<{
        relatorios: Array<RelatorioPDF>;
        resumoFinanceiro: ResumoFinanceiro;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.gerarRelatorioPDF(to_candid_Status_n12(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n5(this.uploadFile, this.downloadFile, arg1));
                return from_candid_record_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gerarRelatorioPDF(to_candid_Status_n12(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n5(this.uploadFile, this.downloadFile, arg1));
            return from_candid_record_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCliente(arg0: bigint): Promise<Cliente | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCliente(arg0);
                return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCliente(arg0);
            return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDadosCompletos(): Promise<DadosCompletos> {
        if (this.processError) {
            try {
                const result = await this.actor.getDadosCompletos();
                return from_candid_DadosCompletos_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDadosCompletos();
            return from_candid_DadosCompletos_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDadosOrcamentoPDF(arg0: bigint): Promise<{
        rodape?: Rodape;
        empresa: Empresa;
        orcamento: Orcamento;
        imagemAdicional?: FileReference;
        cliente: Cliente;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDadosOrcamentoPDF(arg0);
                return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDadosOrcamentoPDF(arg0);
            return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
        }
    }
    async getEmpresa(): Promise<Empresa | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmpresa();
                return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmpresa();
            return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async getEncomenda(arg0: bigint): Promise<Encomenda | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEncomenda(arg0);
                return from_candid_opt_n39(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEncomenda(arg0);
            return from_candid_opt_n39(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getHistorico(arg0: bigint): Promise<Array<Movimentacao> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistorico(arg0);
                return from_candid_opt_n40(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistorico(arg0);
            return from_candid_opt_n40(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMaterial(arg0: bigint): Promise<Material | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterial(arg0);
                return from_candid_opt_n41(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterial(arg0);
            return from_candid_opt_n41(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrcamento(arg0: bigint): Promise<Orcamento | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrcamento(arg0);
                return from_candid_opt_n42(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrcamento(arg0);
            return from_candid_opt_n42(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrcamentoCompleto(arg0: bigint): Promise<{
        orcamento: Orcamento;
        cliente: Cliente;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrcamentoCompleto(arg0);
                return from_candid_opt_n43(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrcamentoCompleto(arg0);
            return from_candid_opt_n43(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRodape(): Promise<Rodape | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRodape();
                return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRodape();
            return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTabelaPreco(arg0: string): Promise<TabelaPrecoCategoria | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTabelaPreco(arg0);
                return from_candid_opt_n45(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTabelaPreco(arg0);
            return from_candid_opt_n45(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async inserirArtigoAbaixo(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inserirArtigoAbaixo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inserirArtigoAbaixo(arg0, arg1);
            return result;
        }
    }
    async inserirArtigoAcima(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inserirArtigoAcima(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inserirArtigoAcima(arg0, arg1);
            return result;
        }
    }
    async inserirLinhaAbaixo(arg0: string, arg1: bigint, arg2: TabelaPrecoLinha): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inserirLinhaAbaixo(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inserirLinhaAbaixo(arg0, arg1, arg2);
            return result;
        }
    }
    async inserirLinhaAcima(arg0: string, arg1: bigint, arg2: TabelaPrecoLinha): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inserirLinhaAcima(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inserirLinhaAcima(arg0, arg1, arg2);
            return result;
        }
    }
    async isAuthenticated(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAuthenticated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAuthenticated();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async listarBackups(): Promise<Array<BackupInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarBackups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarBackups();
            return result;
        }
    }
    async listarClientes(): Promise<Array<Cliente>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarClientes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarClientes();
            return result;
        }
    }
    async listarGestores(): Promise<Array<Gestor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarGestores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarGestores();
            return result;
        }
    }
    async listarMateriais(): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarMateriais();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarMateriais();
            return result;
        }
    }
    async listarMateriaisComMenorPreco(): Promise<Array<{
        id: bigint;
        nome: string;
        menorPreco?: PrecoFornecedor;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarMateriaisComMenorPreco();
                return from_candid_vec_n46(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarMateriaisComMenorPreco();
            return from_candid_vec_n46(this.uploadFile, this.downloadFile, result);
        }
    }
    async listarOrcamentos(): Promise<Array<Orcamento>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarOrcamentos();
                return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarOrcamentos();
            return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async listarPorGestor(arg0: string): Promise<Array<Encomenda>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarPorGestor(arg0);
                return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarPorGestor(arg0);
            return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async listarPorStatus(arg0: Status): Promise<Array<Encomenda>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarPorStatus(to_candid_Status_n12(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarPorStatus(to_candid_Status_n12(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async listarTabelasPreco(): Promise<Array<TabelaPrecoCategoria>> {
        if (this.processError) {
            try {
                const result = await this.actor.listarTabelasPreco();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listarTabelasPreco();
            return result;
        }
    }
    async moverArtigoParaBaixo(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moverArtigoParaBaixo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moverArtigoParaBaixo(arg0, arg1);
            return result;
        }
    }
    async moverArtigoParaCima(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moverArtigoParaCima(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moverArtigoParaCima(arg0, arg1);
            return result;
        }
    }
    async moverParaStatusAnterior(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moverParaStatusAnterior(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moverParaStatusAnterior(arg0);
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async removerGestor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removerGestor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removerGestor(arg0);
            return result;
        }
    }
    async restaurarBackup(arg0: bigint): Promise<{
        mensagem: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.restaurarBackup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restaurarBackup(arg0);
            return result;
        }
    }
    async salvarDadosCompletos(arg0: DadosCompletos): Promise<{
        mensagem: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.salvarDadosCompletos(to_candid_DadosCompletos_n49(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.salvarDadosCompletos(to_candid_DadosCompletos_n49(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async salvarEmpresa(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.salvarEmpresa(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.salvarEmpresa(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async salvarRodape(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.salvarRodape(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.salvarRodape(arg0);
            return result;
        }
    }
    async salvarTabelaPreco(arg0: string, arg1: Array<TabelaPrecoLinha>, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.salvarTabelaPreco(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.salvarTabelaPreco(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async verificarGestores(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verificarGestores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verificarGestores();
            return result;
        }
    }
    async waitForAutosave(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.waitForAutosave();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.waitForAutosave();
            return result;
        }
    }
}
function from_candid_DadosCompletos_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DadosCompletos): DadosCompletos {
    return from_candid_record_n28(uploadFile, downloadFile, value);
}
function from_candid_Encomenda_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Encomenda): Encomenda {
    return from_candid_record_n16(uploadFile, downloadFile, value);
}
function from_candid_Movimentacao_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Movimentacao): Movimentacao {
    return from_candid_record_n33(uploadFile, downloadFile, value);
}
function from_candid_Orcamento_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Orcamento): Orcamento {
    return from_candid_record_n8(uploadFile, downloadFile, value);
}
function from_candid_RelatorioPDF_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RelatorioPDF): RelatorioPDF {
    return from_candid_record_n22(uploadFile, downloadFile, value);
}
function from_candid_StatusOrcamento_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusOrcamento): StatusOrcamento {
    return from_candid_variant_n10(uploadFile, downloadFile, value);
}
function from_candid_Status_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n18(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(uploadFile, downloadFile, value);
}
function from_candid_opt_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cliente]): Cliente | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Rodape]): Rodape | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Empresa]): Empresa | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        rodape: [] | [_Rodape];
        empresa: _Empresa;
        orcamento: _Orcamento;
        imagemAdicional: [] | [_FileReference];
        cliente: _Cliente;
    }]): {
    rodape?: Rodape;
    empresa: Empresa;
    orcamento: Orcamento;
    imagemAdicional?: FileReference;
    cliente: Cliente;
} | null {
    return value.length === 0 ? null : from_candid_record_n37(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileReference]): FileReference | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Encomenda]): Encomenda | null {
    return value.length === 0 ? null : from_candid_Encomenda_n15(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Movimentacao>]): Array<Movimentacao> | null {
    return value.length === 0 ? null : from_candid_vec_n31(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Material]): Material | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Orcamento]): Orcamento | null {
    return value.length === 0 ? null : from_candid_Orcamento_n7(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        orcamento: _Orcamento;
        cliente: _Cliente;
    }]): {
    orcamento: Orcamento;
    cliente: Cliente;
} | null {
    return value.length === 0 ? null : from_candid_record_n44(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TabelaPrecoCategoria]): TabelaPrecoCategoria | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrecoFornecedor]): PrecoFornecedor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mensagem: string;
    encomendaId: [] | [bigint];
    sucesso: boolean;
}): {
    mensagem: string;
    encomendaId?: bigint;
    sucesso: boolean;
} {
    return {
        mensagem: value.mensagem,
        encomendaId: record_opt_to_undefined(from_candid_opt_n2(uploadFile, downloadFile, value.encomendaId)),
        sucesso: value.sucesso
    };
}
function from_candid_record_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    contato: string;
    descricao: string;
    dataCriacao: bigint;
    gestor: string;
    valorAdiantado: bigint;
    nomeCliente: string;
    valorTotal: bigint;
}): {
    id: bigint;
    status: Status;
    contato: string;
    descricao: string;
    dataCriacao: bigint;
    gestor: string;
    valorAdiantado: bigint;
    nomeCliente: string;
    valorTotal: bigint;
} {
    return {
        id: value.id,
        status: from_candid_Status_n17(uploadFile, downloadFile, value.status),
        contato: value.contato,
        descricao: value.descricao,
        dataCriacao: value.dataCriacao,
        gestor: value.gestor,
        valorAdiantado: value.valorAdiantado,
        nomeCliente: value.nomeCliente,
        valorTotal: value.valorTotal
    };
}
function from_candid_record_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    relatorios: Array<_RelatorioPDF>;
    resumoFinanceiro: _ResumoFinanceiro;
}): {
    relatorios: Array<RelatorioPDF>;
    resumoFinanceiro: ResumoFinanceiro;
} {
    return {
        relatorios: from_candid_vec_n20(uploadFile, downloadFile, value.relatorios),
        resumoFinanceiro: value.resumoFinanceiro
    };
}
function from_candid_record_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gestor: string;
    encomendas: Array<_Encomenda>;
}): {
    gestor: string;
    encomendas: Array<Encomenda>;
} {
    return {
        gestor: value.gestor,
        encomendas: from_candid_vec_n14(uploadFile, downloadFile, value.encomendas)
    };
}
function from_candid_record_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientes: Array<_Cliente>;
    lastEditTime: bigint;
    orcamentos: Array<_Orcamento>;
    historico: Array<[bigint, Array<_Movimentacao>]>;
    nextId: bigint;
    gestores: Array<_Gestor>;
    materiais: Array<_Material>;
    encomendas: Array<_Encomenda>;
    tabelasPreco: Array<_TabelaPrecoCategoria>;
    nextOrcamentoId: bigint;
    rodape: [] | [_Rodape];
    nextMaterialId: bigint;
    empresa: [] | [_Empresa];
    nextClienteId: bigint;
    backups: Array<[bigint, string]>;
}): {
    clientes: Array<Cliente>;
    lastEditTime: bigint;
    orcamentos: Array<Orcamento>;
    historico: Array<[bigint, Array<Movimentacao>]>;
    nextId: bigint;
    gestores: Array<Gestor>;
    materiais: Array<Material>;
    encomendas: Array<Encomenda>;
    tabelasPreco: Array<TabelaPrecoCategoria>;
    nextOrcamentoId: bigint;
    rodape?: Rodape;
    nextMaterialId: bigint;
    empresa?: Empresa;
    nextClienteId: bigint;
    backups: Array<[bigint, string]>;
} {
    return {
        clientes: value.clientes,
        lastEditTime: value.lastEditTime,
        orcamentos: from_candid_vec_n6(uploadFile, downloadFile, value.orcamentos),
        historico: from_candid_vec_n29(uploadFile, downloadFile, value.historico),
        nextId: value.nextId,
        gestores: value.gestores,
        materiais: value.materiais,
        encomendas: from_candid_vec_n14(uploadFile, downloadFile, value.encomendas),
        tabelasPreco: value.tabelasPreco,
        nextOrcamentoId: value.nextOrcamentoId,
        rodape: record_opt_to_undefined(from_candid_opt_n34(uploadFile, downloadFile, value.rodape)),
        nextMaterialId: value.nextMaterialId,
        empresa: record_opt_to_undefined(from_candid_opt_n35(uploadFile, downloadFile, value.empresa)),
        nextClienteId: value.nextClienteId,
        backups: value.backups
    };
}
function from_candid_record_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    statusAnterior: _Status;
    timestamp: bigint;
    novoStatus: _Status;
}): {
    statusAnterior: Status;
    timestamp: bigint;
    novoStatus: Status;
} {
    return {
        statusAnterior: from_candid_Status_n17(uploadFile, downloadFile, value.statusAnterior),
        timestamp: value.timestamp,
        novoStatus: from_candid_Status_n17(uploadFile, downloadFile, value.novoStatus)
    };
}
function from_candid_record_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rodape: [] | [_Rodape];
    empresa: _Empresa;
    orcamento: _Orcamento;
    imagemAdicional: [] | [_FileReference];
    cliente: _Cliente;
}): {
    rodape?: Rodape;
    empresa: Empresa;
    orcamento: Orcamento;
    imagemAdicional?: FileReference;
    cliente: Cliente;
} {
    return {
        rodape: record_opt_to_undefined(from_candid_opt_n34(uploadFile, downloadFile, value.rodape)),
        empresa: value.empresa,
        orcamento: from_candid_Orcamento_n7(uploadFile, downloadFile, value.orcamento),
        imagemAdicional: record_opt_to_undefined(from_candid_opt_n38(uploadFile, downloadFile, value.imagemAdicional)),
        cliente: value.cliente
    };
}
function from_candid_record_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orcamento: _Orcamento;
    cliente: _Cliente;
}): {
    orcamento: Orcamento;
    cliente: Cliente;
} {
    return {
        orcamento: from_candid_Orcamento_n7(uploadFile, downloadFile, value.orcamento),
        cliente: value.cliente
    };
}
function from_candid_record_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    nome: string;
    menorPreco: [] | [_PrecoFornecedor];
}): {
    id: bigint;
    nome: string;
    menorPreco?: PrecoFornecedor;
} {
    return {
        id: value.id,
        nome: value.nome,
        menorPreco: record_opt_to_undefined(from_candid_opt_n48(uploadFile, downloadFile, value.menorPreco))
    };
}
function from_candid_record_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    iva: bigint;
    desconto: bigint;
    status: _StatusOrcamento;
    condicoesFornecimento: string;
    imagemAdicionalPath: [] | [string];
    validadeOrcamento: string;
    observacoes: string;
    gestor: string;
    itens: Array<_ItemOrcamento>;
    empresa: _Empresa;
    clienteId: bigint;
    dataOrcamento: bigint;
    valorTotal: bigint;
}): {
    id: bigint;
    iva: bigint;
    desconto: bigint;
    status: StatusOrcamento;
    condicoesFornecimento: string;
    imagemAdicionalPath?: string;
    validadeOrcamento: string;
    observacoes: string;
    gestor: string;
    itens: Array<ItemOrcamento>;
    empresa: Empresa;
    clienteId: bigint;
    dataOrcamento: bigint;
    valorTotal: bigint;
} {
    return {
        id: value.id,
        iva: value.iva,
        desconto: value.desconto,
        status: from_candid_StatusOrcamento_n9(uploadFile, downloadFile, value.status),
        condicoesFornecimento: value.condicoesFornecimento,
        imagemAdicionalPath: record_opt_to_undefined(from_candid_opt_n11(uploadFile, downloadFile, value.imagemAdicionalPath)),
        validadeOrcamento: value.validadeOrcamento,
        observacoes: value.observacoes,
        gestor: value.gestor,
        itens: value.itens,
        empresa: value.empresa,
        clienteId: value.clienteId,
        dataOrcamento: value.dataOrcamento,
        valorTotal: value.valorTotal
    };
}
function from_candid_tuple_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, Array<_Movimentacao>]): [bigint, Array<Movimentacao>] {
    return [
        value[0],
        from_candid_vec_n31(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aceito: null;
} | {
    pendente: null;
} | {
    rejeitado: null;
}): StatusOrcamento {
    return "aceito" in value ? StatusOrcamento.aceito : "pendente" in value ? StatusOrcamento.pendente : "rejeitado" in value ? StatusOrcamento.rejeitado : value;
}
function from_candid_variant_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    encomenda: null;
} | {
    concluido: null;
} | {
    montagem: null;
} | {
    producao: null;
} | {
    porPagar: null;
}): Status {
    return "encomenda" in value ? Status.encomenda : "concluido" in value ? Status.concluido : "montagem" in value ? Status.montagem : "producao" in value ? Status.producao : "porPagar" in value ? Status.porPagar : value;
}
function from_candid_variant_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Encomenda>): Array<Encomenda> {
    return value.map((x)=>from_candid_Encomenda_n15(uploadFile, downloadFile, x));
}
function from_candid_vec_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RelatorioPDF>): Array<RelatorioPDF> {
    return value.map((x)=>from_candid_RelatorioPDF_n21(uploadFile, downloadFile, x));
}
function from_candid_vec_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, Array<_Movimentacao>]>): Array<[bigint, Array<Movimentacao>]> {
    return value.map((x)=>from_candid_tuple_n30(uploadFile, downloadFile, x));
}
function from_candid_vec_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Movimentacao>): Array<Movimentacao> {
    return value.map((x)=>from_candid_Movimentacao_n32(uploadFile, downloadFile, x));
}
function from_candid_vec_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    id: bigint;
    nome: string;
    menorPreco: [] | [_PrecoFornecedor];
}>): Array<{
    id: bigint;
    nome: string;
    menorPreco?: PrecoFornecedor;
}> {
    return value.map((x)=>from_candid_record_n47(uploadFile, downloadFile, x));
}
function from_candid_vec_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Orcamento>): Array<Orcamento> {
    return value.map((x)=>from_candid_Orcamento_n7(uploadFile, downloadFile, x));
}
function to_candid_DadosCompletos_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DadosCompletos): _DadosCompletos {
    return to_candid_record_n50(uploadFile, downloadFile, value);
}
function to_candid_Encomenda_n62(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Encomenda): _Encomenda {
    return to_candid_record_n63(uploadFile, downloadFile, value);
}
function to_candid_Movimentacao_n59(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Movimentacao): _Movimentacao {
    return to_candid_record_n60(uploadFile, downloadFile, value);
}
function to_candid_Orcamento_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Orcamento): _Orcamento {
    return to_candid_record_n53(uploadFile, downloadFile, value);
}
function to_candid_StatusOrcamento_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusOrcamento): _StatusOrcamento {
    return to_candid_variant_n55(uploadFile, downloadFile, value);
}
function to_candid_Status_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n13(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(uploadFile, downloadFile, value);
}
function to_candid_opt_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientes: Array<Cliente>;
    lastEditTime: bigint;
    orcamentos: Array<Orcamento>;
    historico: Array<[bigint, Array<Movimentacao>]>;
    nextId: bigint;
    gestores: Array<Gestor>;
    materiais: Array<Material>;
    encomendas: Array<Encomenda>;
    tabelasPreco: Array<TabelaPrecoCategoria>;
    nextOrcamentoId: bigint;
    rodape?: Rodape;
    nextMaterialId: bigint;
    empresa?: Empresa;
    nextClienteId: bigint;
    backups: Array<[bigint, string]>;
}): {
    clientes: Array<_Cliente>;
    lastEditTime: bigint;
    orcamentos: Array<_Orcamento>;
    historico: Array<[bigint, Array<_Movimentacao>]>;
    nextId: bigint;
    gestores: Array<_Gestor>;
    materiais: Array<_Material>;
    encomendas: Array<_Encomenda>;
    tabelasPreco: Array<_TabelaPrecoCategoria>;
    nextOrcamentoId: bigint;
    rodape: [] | [_Rodape];
    nextMaterialId: bigint;
    empresa: [] | [_Empresa];
    nextClienteId: bigint;
    backups: Array<[bigint, string]>;
} {
    return {
        clientes: value.clientes,
        lastEditTime: value.lastEditTime,
        orcamentos: to_candid_vec_n51(uploadFile, downloadFile, value.orcamentos),
        historico: to_candid_vec_n56(uploadFile, downloadFile, value.historico),
        nextId: value.nextId,
        gestores: value.gestores,
        materiais: value.materiais,
        encomendas: to_candid_vec_n61(uploadFile, downloadFile, value.encomendas),
        tabelasPreco: value.tabelasPreco,
        nextOrcamentoId: value.nextOrcamentoId,
        rodape: value.rodape ? candid_some(value.rodape) : candid_none(),
        nextMaterialId: value.nextMaterialId,
        empresa: value.empresa ? candid_some(value.empresa) : candid_none(),
        nextClienteId: value.nextClienteId,
        backups: value.backups
    };
}
function to_candid_record_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    iva: bigint;
    desconto: bigint;
    status: StatusOrcamento;
    condicoesFornecimento: string;
    imagemAdicionalPath?: string;
    validadeOrcamento: string;
    observacoes: string;
    gestor: string;
    itens: Array<ItemOrcamento>;
    empresa: Empresa;
    clienteId: bigint;
    dataOrcamento: bigint;
    valorTotal: bigint;
}): {
    id: bigint;
    iva: bigint;
    desconto: bigint;
    status: _StatusOrcamento;
    condicoesFornecimento: string;
    imagemAdicionalPath: [] | [string];
    validadeOrcamento: string;
    observacoes: string;
    gestor: string;
    itens: Array<_ItemOrcamento>;
    empresa: _Empresa;
    clienteId: bigint;
    dataOrcamento: bigint;
    valorTotal: bigint;
} {
    return {
        id: value.id,
        iva: value.iva,
        desconto: value.desconto,
        status: to_candid_StatusOrcamento_n54(uploadFile, downloadFile, value.status),
        condicoesFornecimento: value.condicoesFornecimento,
        imagemAdicionalPath: value.imagemAdicionalPath ? candid_some(value.imagemAdicionalPath) : candid_none(),
        validadeOrcamento: value.validadeOrcamento,
        observacoes: value.observacoes,
        gestor: value.gestor,
        itens: value.itens,
        empresa: value.empresa,
        clienteId: value.clienteId,
        dataOrcamento: value.dataOrcamento,
        valorTotal: value.valorTotal
    };
}
function to_candid_record_n60(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    statusAnterior: Status;
    timestamp: bigint;
    novoStatus: Status;
}): {
    statusAnterior: _Status;
    timestamp: bigint;
    novoStatus: _Status;
} {
    return {
        statusAnterior: to_candid_Status_n12(uploadFile, downloadFile, value.statusAnterior),
        timestamp: value.timestamp,
        novoStatus: to_candid_Status_n12(uploadFile, downloadFile, value.novoStatus)
    };
}
function to_candid_record_n63(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Status;
    contato: string;
    descricao: string;
    dataCriacao: bigint;
    gestor: string;
    valorAdiantado: bigint;
    nomeCliente: string;
    valorTotal: bigint;
}): {
    id: bigint;
    status: _Status;
    contato: string;
    descricao: string;
    dataCriacao: bigint;
    gestor: string;
    valorAdiantado: bigint;
    nomeCliente: string;
    valorTotal: bigint;
} {
    return {
        id: value.id,
        status: to_candid_Status_n12(uploadFile, downloadFile, value.status),
        contato: value.contato,
        descricao: value.descricao,
        dataCriacao: value.dataCriacao,
        gestor: value.gestor,
        valorAdiantado: value.valorAdiantado,
        nomeCliente: value.nomeCliente,
        valorTotal: value.valorTotal
    };
}
function to_candid_tuple_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, Array<Movimentacao>]): [bigint, Array<_Movimentacao>] {
    return [
        value[0],
        to_candid_vec_n58(uploadFile, downloadFile, value[1])
    ];
}
function to_candid_variant_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    encomenda: null;
} | {
    concluido: null;
} | {
    montagem: null;
} | {
    producao: null;
} | {
    porPagar: null;
} {
    return value == Status.encomenda ? {
        encomenda: null
    } : value == Status.concluido ? {
        concluido: null
    } : value == Status.montagem ? {
        montagem: null
    } : value == Status.producao ? {
        producao: null
    } : value == Status.porPagar ? {
        porPagar: null
    } : value;
}
function to_candid_variant_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusOrcamento): {
    aceito: null;
} | {
    pendente: null;
} | {
    rejeitado: null;
} {
    return value == StatusOrcamento.aceito ? {
        aceito: null
    } : value == StatusOrcamento.pendente ? {
        pendente: null
    } : value == StatusOrcamento.rejeitado ? {
        rejeitado: null
    } : value;
}
function to_candid_vec_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Orcamento>): Array<_Orcamento> {
    return value.map((x)=>to_candid_Orcamento_n52(uploadFile, downloadFile, x));
}
function to_candid_vec_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, Array<Movimentacao>]>): Array<[bigint, Array<_Movimentacao>]> {
    return value.map((x)=>to_candid_tuple_n57(uploadFile, downloadFile, x));
}
function to_candid_vec_n58(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Movimentacao>): Array<_Movimentacao> {
    return value.map((x)=>to_candid_Movimentacao_n59(uploadFile, downloadFile, x));
}
function to_candid_vec_n61(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Encomenda>): Array<_Encomenda> {
    return value.map((x)=>to_candid_Encomenda_n62(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
